### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by KeyofBlueS** [arp242/find-cursor#17]
Hi,

I encountered a memory leak in find-cursor, this is most noticeable with -r 0 option, it'll slowly exhaust all available system memory.

Thanks.

**Comment by arp242** [comment]
Thanks; I pushed an update which fixes the two leaks that were reported by valgrind. I didn't test extensively with all options, so there could perhaps be others. I'll look in to it further later.

Let me know which options you use if you still see issues after updating.

**Comment by KeyofBlueS** [comment]
Great! fixed now, thanks.

**Comment by arp242** [comment]
Cheerio! I just pushed another update which should give a smoother experience when using `--repeat 0 --follow` to draw a solid circle: instead of creating and destroying new "animated" windows it will just create one window and keep moving it. Reduces CPU consumption on my system from ~3% to 0% and gives a much smoother experience.

Only works if you only add `--transparent` for now.

**Comment by KeyofBlueS** [comment]
After this last commit (https://github.com/arp242/find-cursor/commit/241ae5c0d463985be985978b6787b419c16029ab), `--outline` option seems to not work anymore.

**Comment by arp242** [comment]
Oh right, which options do you use exactly?

**Comment by KeyofBlueS** [comment]
I use `find-cursor -r 0 -f -t -o -w 500 --size 320 --distance 20`

`find-cursor -r 0 -f -t` doesn't print anything
`find-cursor -r 0 -f -t -o` only white lines are printed

**Comment by arp242** [comment]
Hmm, looks like `--transparent` isn't working at all on my system; it shouldn't change anything for that first command though, since that's animated (`size` is different from `distance`; it should only apply when they're the same).

I just reverted it for now, as I can't really be bothered to figure all of this out, and it's a small thing anyway 😅
